#!/bin/bash

# Install google-test
pushd .
git clone --branch=release-1.8.1 --depth=1 https://github.com/google/googletest ~/gtest
mkdir ~/gtest/build && cd ~/gtest/build
cmake ..
make && sudo make install
popd

# For documentation
wget -O - https://bootstrap.pypa.io/get-pip.py | sudo python3.6
