#!/bin/bash
#
# Deploy documentation to Github Pages
#
# Run from project root
#
# @author Natesh Narain
#

export BRANCH=$1
export API_TOKEN=$2

# only deploy on master branch commit
if [[ "$BRANCH" != "master" ]]; then
    exit 0
fi

# Install m.css tool and dependencies
git clone --depth=1 https://github.com/mosra/m.css ~/mcss
python3.6 -m pip install jinja2 --upgrade --user
python3.6 -m pip install Pygments --user

# clone into what is going to be the docs output directory
git clone --branch=gh-pages https://github.com/nnarain/gameboycore.git docs/html

# remove all content of the repo
cd docs/html
git rm -rf .
cd ../..

# build the docs in the cloned directory
python3.6 ~/mcss/doxygen/dox2html5.py Doxyfile-mcss

cd docs/html

# checkin the output
git config user.name "Natesh Narain"
git config user.email nnaraindev@gmail.com
git add . --all
git commit -am "Documentation"

# push
git push -f -q https://nnarain:$API_TOKEN@github.com/nnarain/gameboycore.git gh-pages

cd ../..

#---
echo "Have a nice day"
#---
