/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nnarain_gb_GBCore */

#ifndef _Included_com_nnarain_gb_GBCore
#define _Included_com_nnarain_gb_GBCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nnarain_gb_GBCore
 * Method:    createCore
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nnarain_gb_GBCore_createCore
  (JNIEnv *, jclass);

/*
 * Class:     com_nnarain_gb_GBCore
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nnarain_gb_GBCore_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nnarain_gb_GBCore
 * Method:    loadROM
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_nnarain_gb_GBCore_loadROMBank0
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_nnarain_gb_GBCore
 * Method:    swapROM
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_nnarain_gb_GBCore_swapROM
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_nnarain_gb_GBCore
 * Method:    step
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nnarain_gb_GBCore_step
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
