/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nnarain_gb_resource_GBNativeResource */

#ifndef _Included_com_nnarain_gb_resource_GBNativeResource
#define _Included_com_nnarain_gb_resource_GBNativeResource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nnarain_gb_resource_GBNativeResource
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nnarain_gb_resource_GBNativeResource_release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
