/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nnarain_gb_resource_GBROMParser */

#ifndef _Included_com_nnarain_gb_resource_GBROMParser
#define _Included_com_nnarain_gb_resource_GBROMParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nnarain_gb_resource_GBROMParser
 * Method:    createParser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nnarain_gb_resource_GBROMParser_createParser
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
